name: Go Syntax Check

on:
    push:

jobs:
    syntax-check:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v2

          - name: Setup Go env
            uses: actions/setup-go@v4
            with:
              go-version: 1.23.4

          - name: go tidy
            run: go mod tidy -v

          - name: Check formatting 
            run: test -z "$(gofmt -l .)"

        
        

			
