name: Go Syntax Check

on:
  push: 

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4 

      - name: Go tidy
        run: go mod tidy -v 

      - name: Check formatting
        run: test -z "$(gofmt -l .)"

        
        

			
